//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./currency-converter_types');
//HELPER FUNCTIONS AND STRUCTURES

var CurrencyConverter_convert_args = function(args) {
  this.amount = null;
  this.fromCurrency = null;
  this.toCurrency = null;
  if (args) {
    if (args.amount !== undefined && args.amount !== null) {
      this.amount = args.amount;
    }
    if (args.fromCurrency !== undefined && args.fromCurrency !== null) {
      this.fromCurrency = args.fromCurrency;
    }
    if (args.toCurrency !== undefined && args.toCurrency !== null) {
      this.toCurrency = args.toCurrency;
    }
  }
};
CurrencyConverter_convert_args.prototype = {};
CurrencyConverter_convert_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.DOUBLE) {
        this.amount = input.readDouble();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.fromCurrency = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.toCurrency = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CurrencyConverter_convert_args.prototype.write = function(output) {
  output.writeStructBegin('CurrencyConverter_convert_args');
  if (this.amount !== null && this.amount !== undefined) {
    output.writeFieldBegin('amount', Thrift.Type.DOUBLE, 1);
    output.writeDouble(this.amount);
    output.writeFieldEnd();
  }
  if (this.fromCurrency !== null && this.fromCurrency !== undefined) {
    output.writeFieldBegin('fromCurrency', Thrift.Type.STRING, 2);
    output.writeString(this.fromCurrency);
    output.writeFieldEnd();
  }
  if (this.toCurrency !== null && this.toCurrency !== undefined) {
    output.writeFieldBegin('toCurrency', Thrift.Type.STRING, 3);
    output.writeString(this.toCurrency);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var CurrencyConverter_convert_result = function(args) {
  this.success = null;
  this.err = null;
  if (args instanceof ttypes.RequestError) {
    this.err = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
    if (args.err !== undefined && args.err !== null) {
      this.err = args.err;
    }
  }
};
CurrencyConverter_convert_result.prototype = {};
CurrencyConverter_convert_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.err = new ttypes.RequestError();
        this.err.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CurrencyConverter_convert_result.prototype.write = function(output) {
  output.writeStructBegin('CurrencyConverter_convert_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  if (this.err !== null && this.err !== undefined) {
    output.writeFieldBegin('err', Thrift.Type.STRUCT, 1);
    this.err.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var CurrencyConverterClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
CurrencyConverterClient.prototype = {};
CurrencyConverterClient.prototype.seqid = function() { return this._seqid; };
CurrencyConverterClient.prototype.new_seqid = function() { return this._seqid += 1; };
CurrencyConverterClient.prototype.convert = function(amount, fromCurrency, toCurrency, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_convert(amount, fromCurrency, toCurrency);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_convert(amount, fromCurrency, toCurrency);
  }
};

CurrencyConverterClient.prototype.send_convert = function(amount, fromCurrency, toCurrency) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('convert', Thrift.MessageType.CALL, this.seqid());
  var args = new CurrencyConverter_convert_args();
  args.amount = amount;
  args.fromCurrency = fromCurrency;
  args.toCurrency = toCurrency;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

CurrencyConverterClient.prototype.recv_convert = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new CurrencyConverter_convert_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.err) {
    return callback(result.err);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('convert failed: unknown result');
};
var CurrencyConverterProcessor = exports.Processor = function(handler) {
  this._handler = handler;
}
;
CurrencyConverterProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}
;
CurrencyConverterProcessor.prototype.process_convert = function(seqid, input, output) {
  var args = new CurrencyConverter_convert_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.convert.length === 3) {
    Q.fcall(this._handler.convert, args.amount, args.fromCurrency, args.toCurrency)
      .then(function(result) {
        var result_obj = new CurrencyConverter_convert_result({success: result});
        output.writeMessageBegin("convert", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        if (err instanceof ttypes.RequestError) {
          result = new CurrencyConverter_convert_result(err);
          output.writeMessageBegin("convert", Thrift.MessageType.REPLY, seqid);
        } else {
          result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("convert", Thrift.MessageType.EXCEPTION, seqid);
        }
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.convert(args.amount, args.fromCurrency, args.toCurrency, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined') || err instanceof ttypes.RequestError) {
        result_obj = new CurrencyConverter_convert_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("convert", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("convert", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
